// Sole producer of src/generated/schema.ts (ADR-009).
//
// Uses the openapi-typescript Node API (not its CLI) so the committed
// artifact and the contract check are generated by the identical code path.
// Output is fully deterministic: pinned generator, fixed header, LF line
// endings, single trailing newline.
//
// Usage: node scripts/generate.mjs [input-openapi.json] [output-schema.ts]
// Defaults: ../openapi.json → ../src/generated/schema.ts

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';

const scriptsDir = path.dirname(fileURLToPath(import.meta.url));
const packageDir = path.dirname(scriptsDir);

const [, , inputArg, outputArg] = process.argv;
const input = inputArg
  ? path.resolve(inputArg)
  : path.join(packageDir, 'openapi.json');
const output = outputArg
  ? path.resolve(outputArg)
  : path.join(packageDir, 'src', 'generated', 'schema.ts');

const header = [
  '// Generated by openapi-typescript from openapi.json (ADR-009).',
  '// Do not edit — regenerate with `corepack pnpm generate:client` from the repository root.',
  '',
  '',
].join('\n');

const ast = await openapiTS(pathToFileURL(input));
let contents = header + astToString(ast);
if (!contents.endsWith('\n')) {
  contents += '\n';
}

fs.mkdirSync(path.dirname(output), { recursive: true });
fs.writeFileSync(output, contents);
