// ESLint flat-config baseline (ADR-006).
// Layer 1 (Milestone 0): plain JavaScript over repository scripts/config.
// Layer 2 (Milestone 1B): TypeScript + React + accessibility over apps/**,
// with Next.js rules scoped to the storefront. One root config owns linting
// for the whole workspace; apps do not carry their own ESLint configs.
import js from '@eslint/js';
import next from '@next/eslint-plugin-next';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/',
      '**/dist/',
      '**/.next/',
      '**/coverage/',
      '**/next-env.d.ts', // generated by Next.js
      // Generated API contract (ADR-009): owned by `pnpm generate:client`.
      // Only the generated directory is excluded — the package's facade,
      // scripts, and tests are linted normally.
      'packages/api-client/src/generated/',
    ],
  },
  {
    files: ['**/*.{js,mjs,cjs}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    rules: {
      ...js.configs.recommended.rules,
    },
  },
  {
    // Repository automation scripts run under Node (contract pipeline,
    // dev-stack smoke checks, the E2E orchestrator and its tests).
    files: [
      'scripts/**/*.mjs',
      'packages/*/scripts/**/*.mjs',
      'e2e/scripts/**/*.mjs',
    ],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [tseslint.configs.recommended],
  },
  // NOTE: eslint-plugin-react is deliberately absent — 7.37.x crashes under
  // ESLint 10 (rule-listener construction). Its value is marginal under
  // strict TypeScript; add it back when a release supports ESLint 10.
  {
    files: ['apps/**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
      },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.recommended.rules,
      // ADR-009: applications consume only the api-client facade (its
      // package root). Generated modules stay replaceable internals; the
      // package `exports` map already blocks deep imports at resolution —
      // this rule surfaces the mistake in lint, including relative paths.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@restaurant-engine/api-client/*', '**/api-client/src/*'],
              message:
                'Import only from "@restaurant-engine/api-client" (the facade); generated modules are internal (ADR-009).',
            },
          ],
        },
      ],
    },
  },
  {
    // ADR-016 deep-import hardening: E2E code is black-box. It drives
    // rendered UI and documented HTTP only — no workspace package (the
    // facade included) and no application source may be imported.
    files: ['e2e/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@restaurant-engine/*'],
              message:
                'E2E tests are black-box (ADR-016): drive the UI and documented HTTP, never import workspace packages.',
            },
            {
              group: ['**/apps/*', '**/packages/*', '**/backend/*'],
              message:
                'E2E tests are black-box (ADR-016): application source must not be imported.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['apps/storefront/**/*.{ts,tsx}'],
    plugins: {
      '@next/next': next,
    },
    rules: {
      ...next.configs.recommended.rules,
      ...next.configs['core-web-vitals'].rules,
      // App Router only — there is no pages/ directory to scan.
      '@next/next/no-html-link-for-pages': 'off',
    },
  },
);
