// ESLint flat-config baseline (ADR-006).
// Layer 1 (Milestone 0): plain JavaScript over repository scripts/config.
// Layer 2 (Milestone 1B): TypeScript + React + accessibility over apps/**,
// with Next.js rules scoped to the storefront. One root config owns linting
// for the whole workspace; apps do not carry their own ESLint configs.
import js from '@eslint/js';
import next from '@next/eslint-plugin-next';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/',
      '**/dist/',
      '**/.next/',
      '**/coverage/',
      '**/next-env.d.ts', // generated by Next.js
    ],
  },
  {
    files: ['**/*.{js,mjs,cjs}'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    rules: {
      ...js.configs.recommended.rules,
    },
  },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [tseslint.configs.recommended],
  },
  // NOTE: eslint-plugin-react is deliberately absent — 7.37.x crashes under
  // ESLint 10 (rule-listener construction). Its value is marginal under
  // strict TypeScript; add it back when a release supports ESLint 10.
  {
    files: ['apps/**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': reactHooks,
      'jsx-a11y': jsxA11y,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
      },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.recommended.rules,
    },
  },
  {
    files: ['apps/storefront/**/*.{ts,tsx}'],
    plugins: {
      '@next/next': next,
    },
    rules: {
      ...next.configs.recommended.rules,
      ...next.configs['core-web-vitals'].rules,
      // App Router only — there is no pages/ directory to scan.
      '@next/next/no-html-link-for-pages': 'off',
    },
  },
);
